# once done this will define
# SFML_FOUND
# SFML_INCLUDE_DIRS
# SFML_LIBRARIES
# SFML_DYNAMIC_LIBS

find_path(SFML_INCLUDE_DIR
		  NAMES
		  "SFML/Audio.hpp"
          HINTS "lib/SFML-2.1/include")
          
set(SFML_BIN_DIRS "lib/SFML-2.1/bin")
file(GLOB SFML_DYNAMIC_LIBS "${SFML_BIN_DIRS}/*.dll" "${SFML_BIN_DIRS}/*.so")
find_library(SFML_SND_LIBRARY
			 NAMES libsndfile-1 HINTS ${SFML_BIN_DIRS})
find_library(SFML_AUDIO_LIBRARY
			 NAMES sfml-audio-2 HINTS ${SFML_BIN_DIRS})
find_library(SFML_GRAPHICS_LIBRARY
			 NAMES sfml-graphics-2 HINTS ${SFML_BIN_DIRS})
find_library(SFML_NETWORK_LIBRARY
			 NAMES sfml-network-2 HINTS ${SFML_BIN_DIRS})
find_library(SFML_SYSTEM_LIBRARY
			 NAMES sfml-system-2 HINTS ${SFML_BIN_DIRS})
find_library(SFML_WINDOW_LIBRARY
			 NAMES sfml-window-2 HINTS ${SFML_BIN_DIRS})
find_library(SFML_OPENAL_LIBRARY
			 NAMES openal32 HINTS ${SFML_BIN_DIRS})
			 
set(SFML_INCLUDE_DIRS ${SFML_INCLUDE_DIR})
set(SFML_LIBRARIES
    ${SFML_SND_LIBRARY}
    ${SFML_AUDIO_LIBRARY}
    ${SFML_GRAPHICS_LIBRARY}
    ${SFML_NETWORK_LIBRARY}
    ${SFML_SYSTEM_LIBRARY}
    ${SFML_WINDOW_LIBRARY}
    ${SFML_OPENAL_LIBRARY}
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SFML DEFAULT_MSG
	SFML_INCLUDE_DIR
	SFML_SND_LIBRARY
	SFML_AUDIO_LIBRARY
	SFML_GRAPHICS_LIBRARY
	SFML_NETWORK_LIBRARY
	SFML_SYSTEM_LIBRARY
	SFML_WINDOW_LIBRARY
	SFML_OPENAL_LIBRARY
)

mark_as_advanced(
	SFML_INCLUDE_DIR
	SFML_SND_LIBRARY
	SFML_AUDIO_LIBRARY
	SFML_GRAPHICS_LIBRARY
	SFML_NETWORK_LIBRARY
	SFML_SYSTEM_LIBRARY
	SFML_WINDOW_LIBRARY
	SFML_OPENAL_LIBRARY
)
